# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

age_to_age <- function(cu_index, age1, age1_type, age2_type, y2bh) {
    .Call(`_SIndexR_age_to_age`, cu_index, age1, age1_type, age2_type, y2bh)
}

fiz_check <- function(fiz) {
    .Call(`_SIndexR_fiz_check`, fiz)
}

height_to_index <- function(cu_index, age, age_type, height, si_est_type) {
    .Call(`_SIndexR_height_to_index`, cu_index, age, age_type, height, si_est_type)
}

class_to_index <- function(sp_index, sitecl, fiz) {
    .Call(`_SIndexR_class_to_index`, sp_index, sitecl, fiz)
}

index_to_age <- function(cu_index, site_height, age_type, site_index, y2bh) {
    .Call(`_SIndexR_index_to_age`, cu_index, site_height, age_type, site_index, y2bh)
}

index_to_height <- function(cu_index, iage, age_type, site_index, y2bh, pi) {
    .Call(`_SIndexR_index_to_height`, cu_index, iage, age_type, site_index, y2bh, pi)
}

Sindex_VersionNumber <- function() {
    .Call(`_SIndexR_Sindex_VersionNumber`)
}

Sindex_FirstSpecies <- function() {
    .Call(`_SIndexR_Sindex_FirstSpecies`)
}

Sindex_NextSpecies <- function(sp_index) {
    .Call(`_SIndexR_Sindex_NextSpecies`, sp_index)
}

Sindex_SpecUse <- function(sp_index) {
    .Call(`_SIndexR_Sindex_SpecUse`, sp_index)
}

Sindex_DefCurve <- function(sp_index) {
    .Call(`_SIndexR_Sindex_DefCurve`, sp_index)
}

Sindex_DefGICurve <- function(sp_index) {
    .Call(`_SIndexR_Sindex_DefGICurve`, sp_index)
}

Sindex_DefCurveEst <- function(sp_index, estab) {
    .Call(`_SIndexR_Sindex_DefCurveEst`, sp_index, estab)
}

Sindex_FirstCurve <- function(sp_index) {
    .Call(`_SIndexR_Sindex_FirstCurve`, sp_index)
}

Sindex_NextCurve <- function(sp_index, cu_index) {
    .Call(`_SIndexR_Sindex_NextCurve`, sp_index, cu_index)
}

Sindex_CurveUse <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveUse`, cu_index)
}

Sindex_CurveToSpecies <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveToSpecies`, cu_index)
}

Sindex_SpecCode <- function(sp_index) {
    .Call(`_SIndexR_Sindex_SpecCode`, sp_index)
}

Sindex_SpecName <- function(sp_index) {
    .Call(`_SIndexR_Sindex_SpecName`, sp_index)
}

Sindex_CurveName <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveName`, cu_index)
}

Sindex_CurveSource <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveSource`, cu_index)
}

Sindex_CurveNotes <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveNotes`, cu_index)
}

si_y2bh <- function(cu_index, site_index) {
    .Call(`_SIndexR_si_y2bh`, cu_index, site_index)
}

si_y2bh05 <- function(cu_index, site_index) {
    .Call(`_SIndexR_si_y2bh05`, cu_index, site_index)
}

species_map <- function(sc) {
    .Call(`_SIndexR_species_map`, sc)
}

species_remap <- function(sc, fiz) {
    .Call(`_SIndexR_species_remap`, sc, fiz)
}

