# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

age_to_age <- function(cu_index, age1, age1_type, age2_type, y2bh) {
    .Call(`_SIndexR_age_to_age`, cu_index, age1, age1_type, age2_type, y2bh)
}

fiz_check <- function(fiz) {
    .Call(`_SIndexR_fiz_check`, fiz)
}

height_to_index <- function(cu_index, age, age_type, height, si_est_type) {
    .Call(`_SIndexR_height_to_index`, cu_index, age, age_type, height, si_est_type)
}

class_to_index <- function(sp_index, sitecl, fiz) {
    .Call(`_SIndexR_class_to_index`, sp_index, sitecl, fiz)
}

index_to_age <- function(cu_index, site_height, age_type, site_index, y2bh) {
    .Call(`_SIndexR_index_to_age`, cu_index, site_height, age_type, site_index, y2bh)
}

index_to_height <- function(cu_index, iage, age_type, site_index, y2bh, pi) {
    .Call(`_SIndexR_index_to_height`, cu_index, iage, age_type, site_index, y2bh, pi)
}

Sindex_VersionNumber <- function() {
    .Call(`_SIndexR_Sindex_VersionNumber`)
}

Sindex_FirstSpecies <- function() {
    .Call(`_SIndexR_Sindex_FirstSpecies`)
}

Sindex_NextSpecies <- function(sp_index) {
    .Call(`_SIndexR_Sindex_NextSpecies`, sp_index)
}

Sindex_SpecUse <- function(sp_index) {
    .Call(`_SIndexR_Sindex_SpecUse`, sp_index)
}

Sindex_DefCurve <- function(sp_index) {
    .Call(`_SIndexR_Sindex_DefCurve`, sp_index)
}

Sindex_DefGICurve <- function(sp_index) {
    .Call(`_SIndexR_Sindex_DefGICurve`, sp_index)
}

Sindex_DefCurveEst <- function(sp_index, estab) {
    .Call(`_SIndexR_Sindex_DefCurveEst`, sp_index, estab)
}

Sindex_FirstCurve <- function(sp_index) {
    .Call(`_SIndexR_Sindex_FirstCurve`, sp_index)
}

Sindex_NextCurve <- function(sp_index, cu_index) {
    .Call(`_SIndexR_Sindex_NextCurve`, sp_index, cu_index)
}

#' @title
#' Returns a code telling what functions are available for a curve index.
#' @description
#' Returns a code telling what functions are available for a curve index.
#' @param cu_index Integer, Defines curve index.
#'
#' @return
#'    Integer code.
#'    May return an error code under the following conditions:
#'
#'    return value    condition
#'
#'    ------------    ---------
#'
#'    SI_ERR_CURVE    input curve is not a valid curve index.
#' @note
#'      Code bits are set as follows:
#'      0001: ht = fn (si, age)
#'      0010: si = fn (ht, age)
#'      0100: y2bh = fn (si)
#'      1000: si = fn (ht, age) growth intercept
#' @rdname Sindex_CurveUse
Sindex_CurveUse <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveUse`, cu_index)
}

#' @title
#' Convert curve index to species index
#' @description
#' Returns species index for a given curve index.
#' @param cu_index Integer, Specifies cuive index.
#' @return
#'    Integer species index, for use in other Sindex functions.
#'    May return an error code under the following conditions:
#'
#'    return value    condition
#'
#'    ------------    ---------
#'
#'    SI_ERR_CURVE    input curve is not a valid curve index for any species.
#' @rdname Sindex_CurveToSpecies
Sindex_CurveToSpecies <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveToSpecies`, cu_index)
}

#' @title
#'  Site index conversion between species
#' @description
#'  Site index conversion between species. This function needs to be revised.
#' @param sp_index1 Integer, Source species index.
#' @param site Numeric, Source species site index.
#' @param sp_index2 Integer, Target species index.
#' @return
#'    Floating point target species site index. (computed)
#'
#'  Return Value
#'  ------------
#'    0, or an error code under the following conditions:
#'
#'    return value    condition
#'    ------------    ---------
#'    SI_ERR_SPEC     source or target species index is not valid.
#'    SI_ERR_NO_ANS   there is no conversion defined.
Sindex_SIToSI <- function(sp_index1, site, sp_index2) {
    .Call(`_SIndexR_Sindex_SIToSI`, sp_index1, site, sp_index2)
}

#' @title
#' Returns string containing species code.
#' @description
#' Returns string containing species code.
#' @param sp_index Integer, Specifies species index.
#' @return
#' Pointer to string containing species code.
#'    If input parameter is not a valid species index, the return is the
#'    null pointer.
#' @note
#' Species code string takes the form "Xx" or "Xxx", such as "Sw" or "Fdc".
#' @rdname Sindex_SpecCode
Sindex_SpecCode <- function(sp_index) {
    .Call(`_SIndexR_Sindex_SpecCode`, sp_index)
}

#' @title
#' Returns string containing species name.
#' @description
#' Returns string containing species name.
#' @param sp_index Integer, Specifies species index
#' @return
#'    Pointer to string containing species name.
#'    If input parameter is not a valid species index, the return is the
#'    null pointer.
#'
#' @note
#'    Species name string examples: "Coastal Douglas-fir", "Sitka Spruce".
#' @rdname Sindex_SpecName
Sindex_SpecName <- function(sp_index) {
    .Call(`_SIndexR_Sindex_SpecName`, sp_index)
}

#' @title
#'    Curve name
#' @description
#'    Returns string containing author and date of curve.
#' @param cu_index Integer, Curve index.
#' @return
#'    A string containing curve author and date.
#'    If input parameter is not a valid curve index, the return is the
#'    \code{null}.
#'
#' @note
#'    Curve name string examples: "Bruce (1981)", "Nigh (1998)".
#' @rdname Sindex_CurveName
Sindex_CurveName <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveName`, cu_index)
}

#' @title
#' Curve source
#' @description
#'  Returns string containing publication source.
#' @param cu_index Integer, Curve index.
#' @return
#' String containing publication citation.
#'    If input parameter is not a valid curve index, the return is the
#'    null pointer.
#' @rdname Sindex_CurveSource
Sindex_CurveSource <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveSource`, cu_index)
}

#' @title
#' Curve notes
#' @description
#'    Returns string containing notes on use.
#' @param cu_index Integer, Curve index.
#' @return A string containing notes on use of curve.
#'    If input parameter is not a valid curve index, the return is the
#'    null pointer.
#' @rdname Sindex_CurveNotes
Sindex_CurveNotes <- function(cu_index) {
    .Call(`_SIndexR_Sindex_CurveNotes`, cu_index)
}

si_y2bh <- function(cu_index, site_index) {
    .Call(`_SIndexR_si_y2bh`, cu_index, site_index)
}

si_y2bh05 <- function(cu_index, site_index) {
    .Call(`_SIndexR_si_y2bh05`, cu_index, site_index)
}

species_map <- function(sc) {
    .Call(`_SIndexR_species_map`, sc)
}

species_remap <- function(sc, fiz) {
    .Call(`_SIndexR_species_remap`, sc, fiz)
}

